spring:
  data:
    mongodb:
      uri: mongodb+srv://Pratiksenapati21_db_user:TKEKqN2nOjYw3MmM@cluster0.jgtvinb.mongodb.net/journaldb?appName=Cluster0
      auto-index-creation: true
  main:
    allow-circular-references: true

server:
  port: 8081
  servlet:
    context-path: /journal